//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMall_Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLog
    {
        public int StockLogId { get; set; }
        public int AdminId { get; set; }
        public int WarehouseId { get; set; }
        public int GoodsId { get; set; }
        public int OrderId { get; set; }
        public int VersionId { get; set; }
        public string OperationRecord { get; set; }
        public System.DateTime OperationTime { get; set; }
        public int Stock { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Versions Versions { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
