//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMall_Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versions()
        {
            this.Orders = new HashSet<Orders>();
            this.ShoppingCars = new HashSet<ShoppingCars>();
            this.StockLog = new HashSet<StockLog>();
        }
    
        public int VersionId { get; set; }
        public int GoodsId { get; set; }
        public int WarehouseId { get; set; }
        public string VersionName { get; set; }
        public Nullable<int> ActivationTimes { get; set; }
        public string VersionImage { get; set; }
        public float Price { get; set; }
        public int Stock { get; set; }
        public int Sell { get; set; }
        public int SalesVolume { get; set; }
    
        public virtual Goods Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCars> ShoppingCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockLog> StockLog { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
