//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMall_Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress
    {
        public int DeliveryAddressId { get; set; }
        public int CustomerId { get; set; }
        public string DeliveryName { get; set; }
        public Nullable<int> Default { get; set; }
        public string Province { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string DetailAddress { get; set; }
        public string TelNum { get; set; }
        public string Postcode { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
