//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMall_Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public System.Guid MenuId { get; set; }
        public string Name { get; set; }
        public byte[] Icon { get; set; }
        public string Url { get; set; }
        public string Code { get; set; }
        public System.Guid ParentId { get; set; }
    }
}
